### PR TITLE
FB3

### PR DESCRIPTION
**Pull request by simojo**

### CODE REVIEW

**Comment by gkapfham** [comment]
Hello @simojo and @KellerLiptrap can you please share a status update on this PR? Thanks!

**Comment by gkapfham** [comment]
Also, @simojo and @KellerLiptrap, please note that your build is currently not passing. I investigated this issue and it looks like it is due to the fact that you are attempting to use a colon in the title of an article in the meta-data header for a Markdown file. This is an issue that was confronted by previous article writers. If you check in the existing `.qmd` files for blog posts that we have already published you should find a way to solve this problem. If you have questions about this issue, please let me know. Thanks!

**Comment by simojo** [comment]
@gkapfham this is now fixed.

**Comment by simojo** [comment]
@Finley08 please make your changes to this branch when you're ready.

**Comment by simojo** [comment]
@gkapfham I see now that Finley has created a separate PR (see PR#15). I'm going to merge it into this branch so that this PR is updated.

**Review by gkapfham — CHANGES_REQUESTED** [review]
Hello @simojo and @Finley8 this review of FB3 does not contain any Python source code. If you review the content that we merged and previously discussed for FB2 you will see that it includes technical materials and Python source code. Can you please enhance this review so that it contains more technical content and Python source code? There are a lot of suitable Python source code segments in this article: https://www.fuzzingbook.org/html/Fuzzer.html. You should excerpt at least one of them so that your article offers sufficient technical content.

**Comment by gkapfham** [comment]
Thanks for merging in the PR from Finley, I appreciate your help @simojo. I know that you might not have heard my announcement about the previous article from FB, but it is important for you to know that all of the FB articles need to feature some technical content from Fuzzing Book. Right now, the current draft of the article does not have a sufficient amount of technical content, as I have pointed out in my review. Can you investigate this?

**Comment by simojo** [comment]
Hello @gkapfham, yes; I will start to look back into this starting tomorrow, as it is too late to start anything tonight. I am currently trying to tie some loose ends on another task I am in the middle of.

**Comment by gkapfham** [comment]
Hello @simojo, the new content that you are adding looks great! If you can continue in this fashion, then I think that we will have a suitable article that we can publish to the web site. Thanks for your efforts! @Finley8 can you please help with this article, at minimum by checking it and giving feedback? Finally, @KellerLiptrap when you are able, please make sure to contribute to this article as well. Thanks to you all, I appreciate your efforts.

**Comment by Finley8** [comment]
Ready to be checked by @gkapfham.

**Comment by simojo** [comment]
Sorry Finley, this isn't ready just yet. I'm still fixing a few things in the code department.

**Comment by simojo** [comment]
@gkapfham @Finley8 @KellerLiptrap this is now ready.

**Comment by simojo** [comment]
@gkapfham our 48 hour extension is nearly up; what should we do without this being reviewed?

**Comment by gkapfham** [comment]
It's fine, please don't be concerned. 😉

**Comment by gkapfham** [comment]
Hello @simojo, I will merge this content later today. I regret that I've run into a bunch of pressing issues with other content on the web site that have proven difficult to resolve. With that said, I'll check this content soon and then get back to you and/or merge this later today.

**Pull request merged**
