### PR TITLE
FB2 Blog Post

### PR DESCRIPTION
**Pull request by boulais01**
PR for the FB2 blog post to be written and eventually merged

### CODE REVIEW

**Comment by boulais01** [comment]
@gkapfham Screenshots of what it will look like.
fb2blogpost1
fb2blogpost2

**Review by gkapfham — CHANGES_REQUESTED** [review]
Hello @boulais01, unless I am misunderstanding something, the article for which you were tasked with creating an executive summary of this article: https://www.fuzzingbook.org/html/Coverage.html

Is that correct? If so, then I encourage you to overview some of the technical details that were covered in the FB2 article. For instance, what is coverage? How is coverage calculated for Python programs? Is it better to have a higher or a lower coverage score?

While I think that the content you wrote is certainly a good start, the final executive summary needs some additional technical details. It is also worth noting that there are not a lot of "raw materials" from which you can draw for this article, in regards to a professional precis written by one of your peers in the class. With that said, I don't think that we can move forward with this article until there are some more technical insights in it. Thanks!

**Comment by boulais01** [comment]
PNG uploads aren't processing right now, will upload to Discord and then try again here later.

**Comment by boulais01** [comment]
fb2blogpost1-2
fb2blogpost2-2
fb2blogpost3
fb2blogpost4

**Pull request merged**
