### PR TITLE
FB1

### PR DESCRIPTION
**Pull request by CalebKendra**
This is the FB1 repository, do not push until a blog is added to the `blog/fb1/index.qmd` file

### CODE REVIEW

**Comment by boulais01** [comment]
Potential content to add to this.

```
---
author: CMPSC 203 Class
title: FB1
date: '09/11/2023'
date-format: MM/DD/YYYY
categories: [post, FB, Week 1]
description: <em>Week 1 professional précis for Fuzzing Book.</em>
---

::: {.justify}

This chapter of Fuzzing Book covers the functions and strategies involved in
preparing tests for code, to promote better practices.

:::

{{< include /_back-blog.qmd >}}
```

**Comment by gkapfham** [comment]
Hi! I wanted to check in to see what is the status of this PR? Please be advised that we need this content on the web site no later than 9 AM on Wednesday. It is critical to note that we need to be able to ensure that we have enough time for one or more rounds of review before this PR is merged. Thanks!

**Comment by gkapfham** [comment]
Hello @AlishChhetri and @CalebKendra and @boulais01 is this PR still relevant? If it is not, then can you please let me know so that I can take a step to close the PR and then delete any associated local branches. Thanks for letting me know, I appreciate it.

**Comment by gkapfham** [comment]
I am going to close this PR. If you need to re-open it or create a new PR, please do so.

**Pull request closed without merging**
