### PR TITLE
Fixed typos in FB1 Fall 2024

### PR DESCRIPTION
**Pull request by PCain02**
These are just some touch-ups to our blog page that fixed typos and other errors.

### CODE REVIEW

**Comment by gkapfham** [comment]
Hello @PCain02 and @hemanialaparthi I can't merge this PR. From what I can tell after a brief scan, it looks like this does not incorporate all of my updates and changes. For instance, all of the formatting is not what it should be and what is reflected inside of the main branch for this web site. It is also important to note that it looks like this PR might be (I had a hard time confirming this ...) might be adding some HTML of Jupyter Notebook intermediate files. Finally, it would be better if the PR's commits specifically stated which files are modified.

**Review by gkapfham — CHANGES_REQUESTED** [review]
Please see my prior comment. Unless I am overlooking something, it is possible that this is not working correct in regards to line wraps.

**Comment by gkapfham** [comment]
Hi @PCain02 and @hemanialaparthi is there still content in this that you want to merge?

**Comment by PCain02** [comment]
> Hi @PCain02 and @hemanialaparthi is there still content in this that you want to merge?

Hello, 
So since this PR isn't up to date and we already presented I think it is fine just to close this PR and fix them again later. They did not change the content and were just formalities. I am not sure what you are referring to when you said it added HTML. I think Hemani was only trying to fix the formatting of the links. This PR is really 1 commit in the FB1 blog post to fix typos so sorry it was not clear in the commit itself.

**Pull request closed without merging**
