### PR TITLE
Addition of Policies Tab for Outlining Deadlines And Expectations

### PR DESCRIPTION
**Pull request by boulais01**
image
image

### CODE REVIEW

**Comment by gkapfham** [comment]
Hello @boulais01, thanks for creating this PR. I wanted to quickly check: your screenshot does not show the policies in the tab at the top of the web site. However, my guess is that you are, in fact, expecting that the policies will appear there? Is that correct?

Finally, what strategy do you have in mind when it comes to vetting these policies and ensuring that everyone in our team agrees to them?

Thanks for your contribution and any additional insights that you can share, I really appreciate it!

**Comment by boulais01** [comment]
@gkapfham It is indeed my intention for it to appear as a tab - I hadn't noticed before that it didn't in the render, do you have any recommendations on how to make that work? And these are the policies from our class discussions, so the content is all those that the class has already agreed to. Any updates can be made through future class discussions, in person or on Discord.

**Comment by gkapfham** [comment]
Hello @boulais01, thanks for making these changes. I regret that I have not yet had time to merge them into the main trunk of the web site and then release an updated version of the site to Netlify. I'm planning to review content in this PR again today and, if all goes well, merge it to the site very soon. Thanks again for your patience and your work on this important PR!

**Comment by boulais01** [comment]
@gkapfham I merged main into my fork, which should make your review easier.

**Pull request merged**
